### ISSUE TITLE
GitLab auth does not redirect back to native iOS app

### ISSUE THREAD

**Issue by JJJ** [mattermost/ios#41] opened 2016-10-10 08:50 UTC
When logging in via GitLab from the Mattermost iOS app, I'm sent to Safari & my GitLab installation to login/verify the connection, but once that's done, I'm never redirected back to the iOS app. Instead, Mattermost loads in the same Safari tab GitLab was in, leaving the native iOS app unauthenticated, and basically crippled.

It's plausible I missed some redirect configuration somewhere, because it's quite tricky to get everything lined up correctly, but I've been over the documentation a few times and think I've followed all the steps.

It's also plausible that this issue could be either part of Mattermost proper or GitLab, but since the iOS app experience is the one that's negatively affected, I figure I'd start here to let your group confirm before pushing elsewhere.

**Comment by GhostLyrics** [comment] 2016-10-10 13:09
Possibly a duplicate of #36

**Comment by lfbrock** [comment] 2016-10-31 20:56
Hi @JJJ - I think this might be caused by sessions expiring, we have a ticket here to look into the issue: https://mattermost.atlassian.net/browse/PLT-4349

To check, can you try uninstalling and then reinstalling the app to see if it fixes the issue for you?

**Comment by JJJ** [comment] 2016-10-31 21:52
This did fix it for me, in macOS and iOS.

**Comment by jasonblais** [comment] 2016-11-14 18:47
Thanks @JJJ, glad to hear!

Closing to track in Jira instead https://mattermost.atlassian.net/browse/PLT-4349

**Closed by jasonblais** 2016-11-14 18:47 UTC
