### ISSUE TITLE
Attach_device not working

### ISSUE THREAD

**Issue by migue1s** [mattermost/ios#53] opened 2017-04-06 22:37 UTC
I'm currently on iOS 10.x, compiling release/3.5 for the iOS app and have a GitLab mattermost server 3.7. Most features work correctly except for the `attach_device` endpoint. 

I get the following error after that endpoint is being called:
>Error: statusCode=404 data=Optional({"id":"api.context.404.app_error","message":"Sorry, we could not find the page.","detailed_error":"There doesn't appear to be an api call for the url='/api/v3/users/attach_device'.  Typo? are you missing a team_id or user_id as part of the url?","status_code":404})

**Comment by lfbrock** [comment] 2017-04-06 23:02
Hi @migue1s - when are you getting that error? 

Nothing has changed there, so not sure what could be causing it. Push notifications are working on the compiled apps in the app store, so the attach_device seems to be working for us

**Comment by migue1s** [comment] 2017-04-07 13:54
I am getting the error as soon as I log in or restart the app. It seems like many requests are being sent to that endpoint but after a while they will all error out with that json.

**Comment by enahum** [comment] 2017-04-19 13:05
have you tried to hit the above url manually? if so what response do you get?

**Comment by migue1s** [comment] 2017-04-21 14:30
I get the same response as doing it via iOS @enahum. The team/userId isn't being sent, however I tried to manually look them up in the UserDefaults and they simply are never being set nor are they set to be part of the body of the request either... I'm doing a Gitlab login by the way.

![postman](https://cloud.githubusercontent.com/assets/6880267/25281934/f692220a-267c-11e7-9537-352eeab7ed96.png)

After rechecking on iOS, it seems that the following logs are also getting printed out as part of the error handling:
>Failed attaching device id to session
Sorry, we could not find the page.

**Comment by migue1s** [comment] 2017-04-21 14:51
Further testing revealed that this doesn't happen with email/pass auth, only when logging in through gitlab.

**Comment by lindy65** [comment] 2017-04-26 09:18
Hi @migue1s,

The GitLab login for Mattermost was fixed with version 3.8 released April 16th.  Are you still experiencing a problem?

I'm not sure whether GitLab has updated yet but that might be the problem is you're still experiencing this.

**Comment by lindy65** [comment] 2017-05-10 09:12
Hi @migue1s, 

Circling back to find out how it's going and whether your issue is solved?

**Comment by lindy65** [comment] 2017-05-31 08:37
Closing this issue off due to inactivity.  Please feel free to reopen it if you are still experiencing issues.

**Closed by lindy65** 2017-05-31 08:37 UTC
